name: Update Docs

on:
  schedule:
    - cron: "*/3 * * * *"

jobs:
  update-npm:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.ISSUES_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: npx pnpm i

      - name: Run bash
        run: npx pnpm build

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "update docs"
          add: "docs/*"
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUES_TOKEN }}
